<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Incorrect email address or password.' => '',
    'OTP is already enabled' => '',
    'The activation code provided is not valid.' => '',
    'The password reset token provided is not valid.' => '',
    'The provided email address is not valid' => '',
    'The provided password is not valid' => '',
    'This account is protected with two factor authentication, and a valid OTP code is required to change the password.' => '',
    'Token failed to save' => '',
    'Two factor authentication is enabled for this account.' => '',
    'Two-factor is not enabled' => '',
    'You cannot change your email to your current email address' => '',
];
